const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { whenDev } = require("@craco/craco");

module.exports = {
  devServer: {
    port: 3001,
    hot: true,
  },
  webpack: {
    alias: {
      "custom-package": require.resolve("package-v1"),
    },
    configure: (webpackConfig) => {
      whenDev(() => {
        webpackConfig.output = {
          ...webpackConfig.output,
          publicPath: "auto",
        };
      });
      return webpackConfig;
    },
    plugins: {
      add: [
        new HtmlWebpackPlugin({
          inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
          template: "public/index.html",
          excludeChunks: ["Mfe1"], // exclude remote chunk to avoid error in hot reload
          publicPath: "/",
        }),
        new ModuleFederationPlugin({
          name: "Mfe1",
          filename: "remoteEntry.js",
          exposes: {
            "./Mfe1": "./src/Mfe1",
          },
          shared: {
            "custom-package": {
              singleton: true,
              version: "1.0.1",
              requiredVersion: "^1.0.1",
            },
          },
        }),
      ],
      remove: ["HtmlWebpackPlugin"],
    },
  },
};
